version: '3.8'

services:
  articles_tags:
    container_name: articles-tags
    build:
      context: .
      dockerfile: Dockerfile
      target: local-development
    image: articles-tags
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./setup.cfg:/root/.config/flake8
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
